"""
title: ContextVideo (Local VideoContext Engine)
author: Dolphin Creator
author_url: https://github.com/dolphin-creator/VideoContext-Engine
description: Connects to local VideoContextEngine v3.19 to analyze videos. / Se connecte au moteur local VideoContextEngine v3.19 pour l'analyse vidéo.
version: 0.2.7
requirements: requests
license: MIT
"""

import re
import requests
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class Tools:
    def __init__(self):
        """Initialize the Tool / Initialisation de l'outil."""
        self.valves = self.Valves()

    class Valves(BaseModel):
        videocontext_base_url: str = Field(
            "http://host.docker.internal:7555",
            description=(
                "Primary URL. Fallbacks to localhost/127.0.0.1 automatically. // "
                "URL principale. Bascule automatiquement sur localhost/127.0.0.1 si échec."
            ),
        )
        timeout_seconds: int = Field(
            900,
            description=(
                "Timeout in seconds (default 15 mins). // "
                "Délai d'attente en secondes (défaut 15 min)."
            ),
        )
        # --- PROMPTS AVEC LIMITES DE MOTS / PROMPTS WITH WORD LIMITS ---
        scene_prompt: str = Field(
            "Décris factuellement ce qui se passe dans la scène à partir des images, en te concentrant sur les gestes, la posture, l'ambiance et le contexte. Maximum 80 mots.",
            description=(
                "Prompt for each scene analysis (VLM). // "
                "Prompt pour l'analyse de chaque scène (VLM)."
            )
        )
        summary_prompt: str = Field(
            "Résume la vidéo de façon claire et concise en t'appuyant sur l'ensemble des scènes. Maximum 120 mots.",
            description=(
                "Prompt for the global summary generated by the engine. // "
                "Prompt pour le résumé global généré par le moteur."
            )
        )
        # --- OPTIMISATION ---
        engine_generate_summary: bool = Field(
            True,
            description=(
                "If True, the engine generates its own summary (useful for long videos). "
                "If False, saves time and lets Open WebUI LLM summarize. // "
                "Si True, le moteur génère son propre résumé (utile pour longues vidéos). "
                "Si False, on gagne du temps et on laisse le LLM Open WebUI faire la synthèse."
            )
        )

    # --- Helpers ----------------------------------------------------------

    def _extract_first_url(self, messages: List[Dict[str, Any]]) -> Optional[str]:
        """
        Find the latest URL posted by the user.
        Trouve la dernière URL postée par l'utilisateur.
        """
        if not messages:
            return None
        url_pattern = re.compile(r"(https?://\S+)")
        for msg in reversed(messages):
            if msg.get("role") == "user" and isinstance(msg.get("content"), str):
                match = url_pattern.search(msg["content"])
                if match:
                    return match.group(1).rstrip(").,]")
        return None

    def _call_engine(self, url: str) -> str:
        """
        Call the VideoContextEngine API.
        Appelle l'API VideoContextEngine.
        """
        urls_to_try = [
            self.valves.videocontext_base_url.rstrip('/'),
            "http://host.docker.internal:7555",
            "http://localhost:7555",
            "http://127.0.0.1:7555"
        ]

        seen = set()
        unique_urls = [x for x in urls_to_try if not (x in seen or seen.add(x))]

        # Convert boolean to string "true"/"false" for API form-data
        gen_sum_str = "true" if self.valves.engine_generate_summary else "false"

        payload = {
            "video_url": url,
            "response_format": "text",
            "skip_audio": "false",
            "skip_visual": "false",
            "generate_summary": gen_sum_str,  # Configurable via Valves
            "visual_user_prompt": self.valves.scene_prompt,
            "summary_user_prompt": self.valves.summary_prompt
        }

        last_error = None

        for base_url in unique_urls:
            endpoint = f"{base_url}/api/v1/analyze"
            try:
                r = requests.post(endpoint, data=payload, timeout=self.valves.timeout_seconds)
                r.raise_for_status()
                return r.text
            except requests.exceptions.ConnectionError:
                continue
            except Exception as e:
                last_error = e
                break

        return f"Error: Could not connect to VideoContextEngine. Tried: {unique_urls}. Details: {last_error}"

    # --- Main Tool Method -------------------------------------------------

    def contextvideo(
        self,
        instruction: str = Field(
            "",
            description=(
                "Specific question about the video. If empty, summarizes content. // "
                "Question spécifique sur la vidéo. Si vide, résume le contenu."
            )
        ),
        __messages__: list = None,
    ) -> str:
        """
        Use this tool when the user shares a video link (YouTube, etc.).
        Utilisez cet outil lorsque l'utilisateur partage un lien vidéo.
        """
        msgs = __messages__ or []
        url = self._extract_first_url(msgs)
        if not url:
            return (
                "❌ ContextVideo: No URL found / Aucune URL trouvée.\n"
                "Please provide a valid video link. / Veuillez fournir un lien vidéo valide."
            )

        report = self._call_engine(url)
        if report.startswith("Error"):
            return f"⚠️ {report}"

        user_intent = instruction.strip() if instruction else "Summarize the video content."

        # French detection logic / Logique de détection du Français
        last_msg_content = ""
        for msg in reversed(msgs):
            if msg.get("role") == "user":
                last_msg_content = str(msg.get("content", "")).lower()
                break

        french_triggers = [" le ", " la ", " les ", " vidéo ", "stp", "analyse", "résumé", "traduit", "quoi", "comment"]
        lang_hint = (
            "IMPORTANT: Answer in FRENCH."
            if any(w in last_msg_content for w in french_triggers)
            else "Answer in the user's language."
        )

        return (
            f"[ContextVideo Report] URL: {url}\n"
            f"--------------------------------------------------\n"
            f"{report}\n"
            f"--------------------------------------------------\n"
            f"SYSTEM INSTRUCTION / INSTRUCTION SYSTÈME:\n"
            f"1. Use the report above as absolute truth. / Utilisez le rapport ci-dessus comme vérité absolue.\n"
            f"2. Task / Tâche : {user_intent}\n"
            f"3. {lang_hint}"
        )
